CREATE DATABASE TRY;

USE TRY;

CREATE TABLE EMPLOYEES
 ( 
EMPLOYEE_ID INT AUTO_INCREMENT PRIMARY KEY, 
NAME VARCHAR(100), 
POSITION VARCHAR (100), 
SALARY DECIMAL (10, 2), 
HIRE_DATE DATE 
); 


CREATE TABLE EMPLOYEE_AUDIT
 (
    AUDIT_ID INT AUTO_INCREMENT PRIMARY KEY,
    EMPLOYEE_ID INT,
    NAME VARCHAR(100),
    POSITION VARCHAR(100),
    SALARY DECIMAL(10, 2),
    HIRE_DATE DATE,
    AUDIT_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


INSERT INTO employees (name, position, salary, hire_date) 
VALUES ('John Doe','Software Engineer', 80000.00, '2022-01-15'), 
('Jane Smith', 'Project Manager', 90000.00, '2021-05-22'), 
('Alice Johnson', 'UX Designer', 75000.00, '2023-03-01');

DELIMITER ##

CREATE TRIGGER AF_INS AFTER INSERT ON EMPLOYEES FOR EACH ROW
BEGIN 
   INSERT INTO EMPLOYEE_AUDIT
   (EMPLOYEE_ID, NAME, POSITION, SALARY, HIRE_DATE)
   VALUES (NEW.EMPLOYEE_ID, NEW.NAME, NEW.POSITION, NEW.SALARY, NEW.HIRE_DATE);
END ##
DELIMITER ;


INSERT INTO employees (name, position, salary, hire_date) 
VALUES ( 'ABAB', 'DATA ANALYST', 35000, '2022-02-07');



